<template>
  <div
    :style="{position: 'relative', backgroundColor: '#000', width: '100%', height: '64rem', overflowY: 'auto', textAlign: 'left', fontSize: '1.25rem', color: '#fff', fontFamily: 'Roboto'}"
  >
    <b
      :style="{position: 'absolute', top: '22.38rem', left: 'calc(50% + 323px)', fontSize: '1.75rem', textTransform: 'uppercase', display: 'none', color: '#000', textAlign: 'center'}"
      >Offers / Home Banner</b
    >
    <img
      :style="{position: 'absolute', top: '24.44rem', left: '40.31rem', width: '9.38rem', height: '2.5rem', objectFit: 'cover'}"
      alt=""
      src="/group-758530575@2x.png"
    />
    <div
      :style="{position: 'absolute', top: '2.31rem', left: '6.44rem', width: '12.44rem', height: '2.08rem'}"
    >
      <b
        :style="{position: 'absolute', top: '0rem', left: '0rem', textTransform: 'uppercase'}"
        >explore / Trending</b
      >
      <div
        :style="{position: 'absolute', width: '100%', right: '0%', bottom: '0rem', left: '0%', backgroundColor: '#fff', height: '0.21rem'}"
      />
    </div>
    <div
      :style="{position: 'absolute', top: '33.94rem', left: '5.19rem', width: '4.5rem', height: '2.08rem'}"
    >
      <b
        :style="{position: 'absolute', top: '0rem', left: '0rem', textTransform: 'uppercase'}"
        >City #1</b
      >
      <div
        :style="{position: 'absolute', height: '9.94%', width: '100%', top: '90.06%', right: '0%', bottom: '0%', left: '0%', backgroundColor: '#fff'}"
      />
    </div>
    <div
      :style="{position: 'absolute', top: '6.63rem', left: '5.19rem', display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: '0.81rem'}"
    >
      <Property1Variant31
        imageDimensions="/mask-group@2x.png"
        imageId="/group-1@2x.png"
        :groupIcon="false"
        property1Variant3Width="25rem"
        property1Variant3Height="20.06rem"
        property1Variant3Position="relative"
        property1Variant3Cursor="pointer"
        groupDivWidth="0rem"
        groupDivHeight="0rem"
        loremIpsumDolorFontSize="1.13rem"
        loremIpsumDolorLineHeight="2.19rem"
        sLVsBANFontSize="0.88rem"
        sLVsBANLineHeight="1.53rem"
        divFontSize="3.88rem"
        divLineHeight="3.25rem"
        :onImageContainer8Click="onImageContainerClick"
      /><Property1Variant31
        imageDimensions="/mask-group@2x.png"
        imageId="/group-1@2x.png"
        :groupIcon="false"
        property1Variant3Width="25rem"
        property1Variant3Height="20.06rem"
        property1Variant3Position="relative"
        property1Variant3Cursor="unset"
        groupDivWidth="0rem"
        groupDivHeight="0rem"
        loremIpsumDolorFontSize="1.13rem"
        loremIpsumDolorLineHeight="2.19rem"
        sLVsBANFontSize="0.88rem"
        sLVsBANLineHeight="1.53rem"
        divFontSize="3.88rem"
        divLineHeight="3.25rem"
      /><Property1Variant31
        imageDimensions="/mask-group@2x.png"
        imageId="/group-1@2x.png"
        :groupIcon="false"
        property1Variant3Width="25rem"
        property1Variant3Height="20.06rem"
        property1Variant3Position="relative"
        property1Variant3Cursor="unset"
        groupDivWidth="0rem"
        groupDivHeight="0rem"
        loremIpsumDolorFontSize="1.13rem"
        loremIpsumDolorLineHeight="2.19rem"
        sLVsBANFontSize="0.88rem"
        sLVsBANLineHeight="1.53rem"
        divFontSize="3.88rem"
        divLineHeight="3.25rem"
      /><Property1Variant31
        imageDimensions="/mask-group@2x.png"
        imageId="/group-1@2x.png"
        :groupIcon="false"
        property1Variant3Width="25rem"
        property1Variant3Height="20.06rem"
        property1Variant3Position="relative"
        property1Variant3Cursor="unset"
        groupDivWidth="0rem"
        groupDivHeight="0rem"
        loremIpsumDolorFontSize="1.13rem"
        loremIpsumDolorLineHeight="2.19rem"
        sLVsBANFontSize="0.88rem"
        sLVsBANLineHeight="1.53rem"
        divFontSize="3.88rem"
        divLineHeight="3.25rem"
      /><Property1Variant31
        imageDimensions="/mask-group@2x.png"
        imageId="/group-1@2x.png"
        :groupIcon="false"
        property1Variant3Width="25rem"
        property1Variant3Height="20.06rem"
        property1Variant3Position="relative"
        property1Variant3Cursor="unset"
        groupDivWidth="0rem"
        groupDivHeight="0rem"
        loremIpsumDolorFontSize="1.13rem"
        loremIpsumDolorLineHeight="2.19rem"
        sLVsBANFontSize="0.88rem"
        sLVsBANLineHeight="1.53rem"
        divFontSize="3.88rem"
        divLineHeight="3.25rem"
      /><Property1Variant31
        imageDimensions="/mask-group@2x.png"
        imageId="/group-1@2x.png"
        :groupIcon="false"
        property1Variant3Width="25rem"
        property1Variant3Height="20.06rem"
        property1Variant3Position="relative"
        property1Variant3Cursor="unset"
        groupDivWidth="0rem"
        groupDivHeight="0rem"
        loremIpsumDolorFontSize="1.13rem"
        loremIpsumDolorLineHeight="2.19rem"
        sLVsBANFontSize="0.88rem"
        sLVsBANLineHeight="1.53rem"
        divFontSize="3.88rem"
        divLineHeight="3.25rem"
      /><Property1Variant31
        imageDimensions="/mask-group@2x.png"
        imageId="/group-1@2x.png"
        :groupIcon="false"
        property1Variant3Width="25rem"
        property1Variant3Height="20.06rem"
        property1Variant3Position="relative"
        property1Variant3Cursor="unset"
        groupDivWidth="0rem"
        groupDivHeight="0rem"
        loremIpsumDolorFontSize="1.13rem"
        loremIpsumDolorLineHeight="2.19rem"
        sLVsBANFontSize="0.88rem"
        sLVsBANLineHeight="1.53rem"
        divFontSize="3.88rem"
        divLineHeight="3.25rem"
      /><Property1Variant31
        imageDimensions="/mask-group@2x.png"
        imageId="/group-1@2x.png"
        :groupIcon="false"
        property1Variant3Width="25rem"
        property1Variant3Height="20.06rem"
        property1Variant3Position="relative"
        property1Variant3Cursor="unset"
        groupDivWidth="0rem"
        groupDivHeight="0rem"
        loremIpsumDolorFontSize="1.13rem"
        loremIpsumDolorLineHeight="2.19rem"
        sLVsBANFontSize="0.88rem"
        sLVsBANLineHeight="1.53rem"
        divFontSize="3.88rem"
        divLineHeight="3.25rem"
      />
    </div>
    <div
      :style="{position: 'absolute', top: '39.13rem', left: '5.19rem', width: '205.69rem', height: '20.06rem'}"
    >
      <div
        :style="{position: 'absolute', top: '0rem', left: '0rem', display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: '0.81rem'}"
      >
        <Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        />
      </div>
    </div>
    <ImageVariant2
      imageDimensions="/mask-group@2x.png"
      imageVariant2Width="35.76%"
      imageVariant2Height="40.54%"
      imageVariant2Position="absolute"
      imageVariant2Top="58.2%"
      imageVariant2Right="35.9%"
      imageVariant2Bottom="1.26%"
      imageVariant2Left="28.33%"
      groupDivLeft="2.51rem"
      groupDivWidth="17.77rem"
      loremIpsumDolorLeft="3.46rem"
      loremIpsumDolorFontSize="1.13rem"
      loremIpsumDolorLineHeight="1.69rem"
      sLVsBANFontSize="0.88rem"
      sLVsBANLineHeight="1.33rem"
      divFontSize="4.59rem"
      divLineHeight="3.86rem"
    /><Navigation
      dimensionLabel="/group-1000002298@2x.png"
      property1DefaultWidth="10.63rem"
      property1DefaultHeight="64rem"
      property1DefaultPosition="absolute"
      property1DefaultTop="1.25rem"
      property1DefaultLeft="1.25rem"
      searchFontSize="1rem"
      searchFontSize1="1rem"
      searchFontSize2="1rem"
      searchFontSize3="1rem"
      searchFontSize4="1rem"
      searchFontSize5="1rem"
      searchFontSize6="1rem"
      :onGroupContainerClick="onGroupContainer20Click"
      :onGroupContainer1Click="onGroupContainer21Click"
      :onGroupContainer2Click="onGroupContainer22Click"
      :onGroupContainer3Click="onGroupContainer23Click"
      :onGroupContainer4Click="onGroupContainer24Click"
      :onGroupContainer5Click="onGroupContainer25Click"
      :showSearch="false"
    />
  </div>
</template>
<script lang="ts">
  import { defineComponent } from "vue";
  import Property1Variant31 from "../components/Property1Variant31.vue";
  import ImageVariant2 from "../components/ImageVariant2.vue";
  import Navigation from "../components/Navigation.vue";

  export default defineComponent({
    name: "Page2B11",
    components: { Property1Variant31, ImageVariant2, Navigation },
    methods: {

      // CTA - CONVERSATIONS
      onImageContainerClick() {
        this.$router.push("/page-3a");
      },

      onGroupContainer20Click() {
        this.$router.push("/page-12");
      },
      onGroupContainer21Click() {
        this.$router.push("/page-6");
      },
      onGroupContainer22Click() {
        this.$router.push("/page-2b1");
      },
      onGroupContainer23Click() {
        this.$router.push("/page-2b");
      },
      onGroupContainer24Click() {
        this.$router.push("/page-2a");
      },
      onGroupContainer25Click() {
        this.$router.push("/page-4b");
      },
    },
  });
</script>
