<template>
  <div
    :style="{position: 'relative', backgroundColor: '#000', width: '100%', height: '64rem', overflowY: 'auto', textAlign: 'left', fontSize: '1.25rem', color: '#fff', fontFamily: 'Roboto'}"
  >
    <img
      :style="{position: 'absolute', top: '24.44rem', left: '40.31rem', width: '9.38rem', height: '2.5rem', objectFit: 'cover'}"
      alt=""
      src="/group-758530575@2x.png"
    />
    <div
      :style="{position: 'absolute', top: '3.44rem', left: '5.19rem', width: '205.69rem', height: '76.88rem'}"
    >
      <div
        :style="{position: 'absolute', top: '0rem', left: '0rem', width: '4.63rem', height: '2.08rem'}"
      >
        <b
          :style="{position: 'absolute', top: '0rem', left: '0rem', textTransform: 'uppercase'}"
          >MyLIGr</b
        >
        <div
          :style="{position: 'absolute', height: '9.91%', width: '100%', top: '90.09%', right: '0%', bottom: '0%', left: '0%', backgroundColor: '#fff'}"
        />
      </div>
      <div
        :style="{position: 'absolute', top: '0rem', left: '7.13rem', width: '5.38rem', height: '2.08rem', opacity: '0.5'}"
      >
        <div
          :style="{position: 'absolute', top: '0rem', left: '0rem', textTransform: 'uppercase'}"
        >
          explore
        </div>
        <div
          :style="{position: 'absolute', height: '9.94%', width: '100%', top: '90.06%', right: '0%', bottom: '0%', left: '0%', backgroundColor: '#fff'}"
        />
      </div>
      <b
        :style="{position: 'absolute', top: '53.5rem', left: '0rem', fontSize: '1.5rem', textTransform: 'uppercase'}"
        >Special Events</b
      >
      <div
        :style="{position: 'absolute', top: '56.81rem', left: '0rem', display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: '0.81rem'}"
      >
        <Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        />
      </div>
      <div
        :style="{position: 'absolute', top: '4.44rem', left: '0rem', display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: '0.81rem', textAlign: 'center', fontSize: '1.13rem'}"
      >
        <Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="pointer"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
          :onImageContainer8Click="onImageContainer8Click"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="true"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        />
        <div
          :style="{position: 'relative', width: '25rem', height: '20.06rem', display: 'none'}"
        >
          <img
            :style="{position: 'absolute', height: '71.65%', width: '100%', top: '0%', right: '0%', bottom: '28.35%', left: '0%', maxWidth: '100%', overflow: 'hidden', maxHeight: '100%', objectFit: 'cover'}"
            alt=""
            src="/mask-group@2x.png"
          />
          <div
            :style="{position: 'absolute', top: '74.77%', left: '28%', width: '0rem', height: '0rem'}"
          >
            <div
              :style="{position: 'absolute', letterSpacing: '0.26px', lineHeight: '2.19rem', fontWeight: '500', display: 'none'}"
            >
              Lorem ipsum dolor sit amet
            </div>
            <div
              :style="{position: 'absolute', fontSize: '0.88rem', letterSpacing: '0.26px', lineHeight: '1.53rem', fontWeight: '500', color: '#ff0000', display: 'none'}"
            >
              SL vs BAN Live Updates(AP)
            </div>
            <div
              :style="{position: 'absolute', fontSize: '3.88rem', letterSpacing: '0.39px', lineHeight: '3.25rem', fontWeight: '900', display: 'none'}"
            >
              2
            </div>
          </div>
          <img
            :style="{position: 'absolute', height: '14.33%', width: '11.5%', top: '28.66%', right: '44.25%', bottom: '57.01%', left: '44.25%', maxWidth: '100%', overflow: 'hidden', maxHeight: '100%', objectFit: 'cover'}"
            alt=""
            src="/group-1@2x.png"
          />
        </div>
        <Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="true"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        /><Property1Variant31
          imageDimensions="/mask-group@2x.png"
          imageId="/group-1@2x.png"
          :groupIcon="false"
          property1Variant3Width="25rem"
          property1Variant3Height="20.06rem"
          property1Variant3Position="relative"
          property1Variant3Cursor="unset"
          groupDivWidth="0rem"
          groupDivHeight="0rem"
          loremIpsumDolorFontSize="1.13rem"
          loremIpsumDolorLineHeight="2.19rem"
          sLVsBANFontSize="0.88rem"
          sLVsBANLineHeight="1.53rem"
          divFontSize="3.88rem"
          divLineHeight="3.25rem"
        />
      </div>
      <div
        :style="{position: 'absolute', top: '28.81rem', left: '0rem', width: '205.69rem', height: '20.06rem'}"
      >
        <div
          :style="{position: 'absolute', top: '0rem', left: '0rem', display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: '0.81rem'}"
        >
          <Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          />
        </div>
      </div>
      <ImageVariant2
        imageDimensions="/mask-group@2x.png"
        imageVariant2Width="15.65%"
        imageVariant2Height="33.75%"
        imageVariant2Position="absolute"
        imageVariant2Top="35.04%"
        imageVariant2Right="74.48%"
        imageVariant2Bottom="31.21%"
        imageVariant2Left="9.88%"
        groupDivLeft="2.51rem"
        groupDivWidth="17.77rem"
        loremIpsumDolorLeft="3.46rem"
        loremIpsumDolorFontSize="1.13rem"
        loremIpsumDolorLineHeight="1.69rem"
        sLVsBANFontSize="0.88rem"
        sLVsBANLineHeight="1.33rem"
        divFontSize="4.59rem"
        divLineHeight="3.86rem"
      />
    </div>
    <Navigation
      dimensionLabel="/group-1000002298@2x.png"
      property1DefaultWidth="10.63rem"
      property1DefaultHeight="64rem"
      property1DefaultPosition="absolute"
      property1DefaultTop="1.25rem"
      property1DefaultLeft="1.25rem"
      searchFontSize="1rem"
      searchFontSize1="1rem"
      searchFontSize2="1rem"
      searchFontSize3="1rem"
      searchFontSize4="1rem"
      searchFontSize5="1rem"
      searchFontSize6="1rem"
      :onGroupContainerClick="onGroupContainer30Click"
      :onGroupContainer1Click="onGroupContainer31Click"
      :onGroupContainer2Click="onGroupContainer32Click"
      :onGroupContainer3Click="onGroupContainer33Click"
      :onGroupContainer4Click="onGroupContainer34Click"
      :onGroupContainer5Click="onGroupContainer35Click"
      :showSearch="false"
    />
  </div>
</template>
<script lang="ts">
  import { defineComponent } from "vue";
  import Property1Variant31 from "../components/Property1Variant31.vue";
  import ImageVariant2 from "../components/ImageVariant2.vue";
  import Navigation from "../components/Navigation.vue";

  export default defineComponent({
    name: "Page2A",
    components: { Property1Variant31, ImageVariant2, Navigation },
    methods: {
      onImageContainer8Click() {
        this.$router.push("/");
      },
      onGroupContainer30Click() {
        this.$router.push("/page-12");
      },
      onGroupContainer31Click() {
        this.$router.push("/page-6");
      },
      onGroupContainer32Click() {
        this.$router.push("/page-2b1");
      },
      onGroupContainer33Click() {
        this.$router.push("/page-2b");
      },
      onGroupContainer34Click() {
        this.$router.push("/page-2a");
      },
      onGroupContainer35Click() {
        this.$router.push("/page-4b");
      },
    },
  });
</script>
