<template>
  <div
    :style="{position: 'relative', backgroundColor: '#000', width: '100%', height: '64rem', overflowY: 'auto', textAlign: 'left', fontSize: '1.38rem', color: '#fff', fontFamily: 'Roboto'}"
  >
    <Property1DefaultImage
      property1DefaultIconWidth="83.13rem"
      property1DefaultIconHeight="35.63rem"
      property1DefaultIconPosition="absolute"
      property1DefaultIconTop="2.25rem"
      property1DefaultIconLeft="5.44rem"
    />
    <div
      :style="{position: 'absolute', height: '35.55%', width: '228.54%', top: '105.37%', right: '-134.31%', bottom: '-40.92%', left: '5.76%'}"
    >
      <b
        :style="{position: 'absolute', top: '0%', left: '0%', textTransform: 'uppercase'}"
        >Foot ball</b
      >
      <div
        :style="{position: 'absolute', top: '2.69rem', left: '0rem', width: '205.69rem', height: '20.06rem'}"
      >
        <div
          :style="{position: 'absolute', top: '0rem', left: '0rem', display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: '0.81rem'}"
        >
          <Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          />
        </div>
      </div>
    </div>
    <div
      :style="{position: 'absolute', height: '42.49%', width: '228.54%', top: '63.09%', right: '-134.31%', bottom: '-5.58%', left: '5.76%'}"
    >
      <b
        :style="{position: 'absolute', top: '0%', left: '0%', textTransform: 'uppercase'}"
        >Cricket</b
      >
      <div
        :style="{position: 'absolute', top: '3.13rem', left: '0rem', width: '205.69rem', height: '20.06rem'}"
      >
        <div
          :style="{position: 'absolute', top: '0rem', left: '0rem', display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: '0.81rem'}"
        >
          <Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="pointer"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
            :onImageContainer8Click="onImageContainer8Click"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          /><Property1Variant31
            imageDimensions="/mask-group@2x.png"
            imageId="/group-1@2x.png"
            :groupIcon="false"
            property1Variant3Width="25rem"
            property1Variant3Height="20.06rem"
            property1Variant3Position="relative"
            property1Variant3Cursor="unset"
            groupDivWidth="0rem"
            groupDivHeight="0rem"
            loremIpsumDolorFontSize="1.13rem"
            loremIpsumDolorLineHeight="2.19rem"
            sLVsBANFontSize="0.88rem"
            sLVsBANLineHeight="1.53rem"
            divFontSize="3.88rem"
            divLineHeight="3.25rem"
          />
        </div>
      </div>
      <ImageVariant2
        imageDimensions="/mask-group@2x.png"
        imageVariant2Width="15.65%"
        imageVariant2Height="95.4%"
        imageVariant2Position="absolute"
        imageVariant2Top="4.6%"
        imageVariant2Right="74.48%"
        imageVariant2Bottom="0%"
        imageVariant2Left="9.88%"
        groupDivLeft="2.51rem"
        groupDivWidth="17.77rem"
        loremIpsumDolorLeft="3.46rem"
        loremIpsumDolorFontSize="1.13rem"
        loremIpsumDolorLineHeight="1.69rem"
        sLVsBANFontSize="0.88rem"
        sLVsBANLineHeight="1.33rem"
        divFontSize="4.59rem"
        divLineHeight="3.86rem"
      />
    </div>
    <b
      :style="{position: 'absolute', top: '56.25%', left: '5.76%', textTransform: 'uppercase'}"
      >Cricket</b
    >
    <b
      :style="{position: 'absolute', top: '96.58%', left: '5.76%', textTransform: 'uppercase'}"
      >Foot ball</b
    >
    <b
      :style="{position: 'absolute', top: '22.38rem', left: 'calc(50% - 637px)', fontSize: '1.75rem', textTransform: 'uppercase', display: 'none', color: '#000', textAlign: 'center'}"
      >Offers / Home Banner</b
    ><Property1Variant3
      property1Variant3Width="10.63rem"
      property1Variant3Height="64rem"
      property1Variant3Position="absolute"
      property1Variant3Top="0rem"
      property1Variant3Left="1.88rem"
      playButtonTop="1.19rem"
      playButtonLeft="1.19rem"
      playButtonWidth="3rem"
      playButtonPadding="0.5rem 1rem 0.5rem 0.75rem"
      chevronRightIconWidth="1.5rem"
      chevronRightIconHeight="1.5rem"
      searchFontSize="1rem"
      searchFontSize1="1rem"
      frameDivGap="0.63rem"
      frameDivWidth="9.38rem"
      frameDivPadding="0rem 0.44rem"
      comediesFontSize="0.94rem"
      comediesLineHeight="2.19rem"
      frameDivWidth1="9.38rem"
      frameDivPadding1="0rem 0.44rem"
      comediesFontSize1="0.94rem"
      comediesLineHeight1="2.19rem"
      frameDivWidth2="9.38rem"
      frameDivPadding2="0rem 0.44rem"
      comediesFontSize2="0.94rem"
      comediesLineHeight2="2.19rem"
      frameDivWidth3="9.38rem"
      frameDivPadding3="0rem 0.44rem"
      comediesFontSize3="0.94rem"
      comediesLineHeight3="2.19rem"
      frameDivWidth4="9.38rem"
      frameDivPadding4="0rem 0.44rem"
      comediesFontSize4="0.94rem"
      comediesLineHeight4="2.19rem"
      frameDivWidth5="9.38rem"
      frameDivPadding5="0rem 0.44rem"
      comediesFontSize5="0.94rem"
      comediesLineHeight5="2.19rem"
      frameDivWidth6="9.38rem"
      frameDivPadding6="0rem 0.44rem"
      comediesFontSize6="0.94rem"
      comediesLineHeight6="2.19rem"
      frameDivWidth7="9.38rem"
      frameDivPadding7="0rem 0.44rem"
      comediesFontSize7="0.94rem"
      comediesLineHeight7="2.19rem"
      frameDivWidth8="9.38rem"
      frameDivPadding8="0rem 0.44rem"
      comediesFontSize8="0.94rem"
      comediesLineHeight8="2.19rem"
    />
  </div>
</template>
<script lang="ts">
  import { defineComponent } from "vue";
  import Property1DefaultImage from "../components/Property1DefaultImage.vue";
  import Property1Variant31 from "../components/Property1Variant31.vue";
  import ImageVariant2 from "../components/ImageVariant2.vue";
  import Property1Variant3 from "../components/Property1Variant3.vue";

  export default defineComponent({
    name: "Page12",
    components: {
      Property1DefaultImage,
      Property1Variant31,
      ImageVariant2,
      Property1Variant3,
    },
    methods: {
      onImageContainer8Click() {
        this.$router.push("/page-11");
      },
    },
  });
</script>
